### ISSUE TITLE
When skipping to the next song, the track info is not updated until the next skip

### ISSUE THREAD

**Issue by martinroger** [martinroger/ipodesp32#4]
When actively skipping, the track info is not updated unless another fwd skip is requested OR the "Track" button is pressed.
Automatic change is not impacted

**Comment by martinroger** [comment]
Will be addressed by specific PR

**Comment by APF-MRoger** [comment]
Fixed in 50ea877a67728276d68b7e3371425ac8521d2902 initially but it broke the PREV/NEXT flip flopping because of a misconception around the prevXXX properties of espod and performing unjustified comparisons to try and determine NEXT/PREV moves when triggered from the phone.

First cleaned fix to be tested in ad4c92ea65b2d87a1674b790854c9f8f80d46cca

**Comment by martinroger** [comment]
Pending Ack until new metadata seems to work OK. Fixed officially in 719ab09c6c69dd3a6eb89c550ffffab03b6c3533
